var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");
var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};$jscomp.polyfill=function(a,c,b,e){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,e):$jscomp.polyfillUnisolated(a,c,b,e))};
$jscomp.polyfillUnisolated=function(a,c,b,e){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in b||(b[d]={});b=b[d]}a=a[a.length-1];e=b[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var g=d[f];g in e||(e[g]={});e=e[g]}d=d[d.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?e[d]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:c}):c!==b&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=$jscomp.propertyToPolyfillSymbol[d],
$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var c=this;c instanceof String&&(c=String(c));var d=c.length;b=b||0;for(0>b&&(b=Math.max(b+d,0));b<d;b++){var f=c[b];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");ALREADY_UPDATED=!1;DEFAULT_BLACKLIST="twitter www.linkedin www.amazon www.facebook www.linkedin mail.google outlook.office mail.aol www.google www.zoho mail.com mail.yahoo www.tiktok www.facebook www.whatsapp www.messenger www.instagram www.tiktok www.ebay www.walmart www.target www.alibaba www.wayfair www.wish www.shopify www.youtube www.netflix docs.google support.google vimeo accounts.google drive.google github www.dropbox www.paypal www.dailymotion news.google bitly bit.ly www.hbo www.hbomax www.hulu www.chase www.bankofamerica www.suntrust www.wellsfargo www.citigroup www.americanexpress www.capitalone www.pnc".split(" ");
LIST_TYPE="blacklisted-edicratic";checkAndRun();setInterval(function(){"undefined"!==typeof currentWebCheckedUrl&&window.location.href!==currentWebCheckedUrl&&(currentWebCheckedUrl=window.location.href,checkAndRun())},1E3);window.location.hostname.includes("yahoo")&&window.addEventListener("scroll",clearYahooTags);function checkAndRun(){chrome.storage.local.get(["auto-webcheck-enabled"],function(a){!1!==a["auto-webcheck-enabled"]&&runAutoCheck()})}
function runAutoCheck(){chrome.storage.local.get([LIST_TYPE],function(a){var c=a[LIST_TYPE]||DEFAULT_BLACKLIST,b=a[LIST_TYPE];chrome.storage.local.get(["authStatus"],function(a){chrome.runtime.lastError||null===a.authStatus||void 0===a.authStatus||"Logged Out"===a.authStatus||(b||(a={},a[LIST_TYPE]=DEFAULT_BLACKLIST,chrome.storage.local.set(a),chrome.storage.local.set({"button-change-edicratic":{time:(new Date).getTime(),on:!0}})),a=getDomain(window.location.href),c.includes(a)?window.removeEventListener("scroll",
checkForSizeChange):makePostRequest(!0))})})}chrome.storage.onChanged.addListener(function(a,c){a["auto-webcheck-enabled"]?a["auto-webcheck-enabled"].newValue&&runAutoCheck():a.authStatus||(a[LIST_TYPE]?(a=a[LIST_TYPE],c=a.newValue,whitelistChange(a.oldValue.length>c.length?"Remove":"Add",c)):a["button-change-edicratic"]?(a=a["button-change-edicratic"],a.oldValue&&autoWebCheckChange(a.oldValue.on?"turnOff":"turnOn",a.newValue.time-a.oldValue.time)):a["dummy-highlight"]&&analyzeTextForSending())});
function clearYahooTags(){for(var a=document.getElementsByClassName("StretchedBox"),c=0;c<a.length;c++)a[c].style.position="relative"}function getDomain(a){var c=document.createElement("a");c.href=a;return c.hostname.replace(/.(com|co.uk|net|org|gov|de|edu)/,"")}function handleUpdate(a){ALREADY_UPDATED||"Extension context invalidated."!==a||(ALREADY_UPDATED=!0,alert("Looks like the extension was just updated. Please reload your page :)"))};
