var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,d){a.raw=d;return a};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<a.length;++d){var e=a[d];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,e){if(a==Array.prototype||a==Object.prototype)return a;a[d]=e.value;return a};$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");
var $jscomp$lookupPolyfilledValue=function(a,d){var e=$jscomp.propertyToPolyfillSymbol[d];if(null==e)return a[d];e=a[e];return void 0!==e?e:a[d]};$jscomp.polyfill=function(a,d,e,c){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,d,e,c):$jscomp.polyfillUnisolated(a,d,e,c))};
$jscomp.polyfillUnisolated=function(a,d,e,c){e=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var b=a[c];b in e||(e[b]={});e=e[b]}a=a[a.length-1];c=e[a];d=d(c);d!=c&&null!=d&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(a,d,e,c){var b=a.split(".");a=1===b.length;c=b[0];c=!a&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<b.length-1;g++){var h=b[g];h in c||(c[h]={});c=c[h]}b=b[b.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?c[b]:null;d=d(e);null!=d&&(a?$jscomp.defineProperty($jscomp.polyfills,b,{configurable:!0,writable:!0,value:d}):d!==e&&($jscomp.propertyToPolyfillSymbol[b]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(b):$jscomp.POLYFILL_PREFIX+b,b=$jscomp.propertyToPolyfillSymbol[b],
$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:d})))};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function d(){this.batch_=null}function e(a){return a instanceof b?a:new b(function(b,h){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;d.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var c=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(a){c(a,0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};d.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var b=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(f){b.reject(f)}};b.prototype.createResolveAndReject_=function(){function a(a){return function(e){c||(c=!0,a.call(b,e))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};b.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};b.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(f){this.reject_(f);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};b.prototype.reject_=function(a){this.settle_(2,a)};b.prototype.fulfill_=function(a){this.settle_(1,a)};b.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};b.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)g.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var g=new d;b.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};b.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};b.prototype.then=function(a,c){function e(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(n){h(n)}}:b}var d,h,l=new b(function(a,b){d=a;h=b});this.callWhenSettled_(e(a,d),e(c,h));return l};
b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.callWhenSettled_=function(a,b){function c(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(c)};b.resolve=e;b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(b,c){for(var d=$jscomp.makeIterator(a),f=d.next();!f.done;f=d.next())e(f.value).callWhenSettled_(b,
c)})};b.all=function(a){var c=$jscomp.makeIterator(a),d=c.next();return d.done?e([]):new b(function(a,b){function k(b){return function(c){f[b]=c;g--;0==g&&a(f)}}var f=[],g=0;do f.push(void 0),g++,e(d.value).callWhenSettled_(k(f.length-1),b),d=c.next();while(!d.done)})};return b},"es6","es3");BASE_URL="https://webcheck-api.edicratic.com";
chrome.runtime.onMessage.addListener(function(a,d,e){"callInternet"===a.message?fetch(a.input,a.params).then(function(a){a.text().then(function(b){e([{body:b,status:a.status,statusText:a.statusText},null])})},function(a){console.log(a);e([null,a])}):"callWebCheckAPI"===a.message?(url=BASE_URL+a.input,fetch(url,a.params).then(function(a){requestFailed=!1;401===a.status?(requestFailed=!0,chrome.storage.local.set({authStatus:"Logged Out"},function(){chrome.runtime.lastError&&console.log("failed to save status, fatal error")})):
200!==a.status&&(requestFailed=!0);a.text().then(function(b){requestFailed?e([null,b]):e([{body:b,status:a.status,statusText:a.statusText},null])})},function(a){console.log(a);e([null,a])})):"NYTimes"===a.message?fetch("https://news.google.com/rss/search?q="+a.term).then(function(a){a.text().then(function(b){e([{body:b,status:a.status,statusText:a.statusText},null])},function(a){e([null,a])})}):"basicGET"===a.message?fetch(a.url).then(function(a){a.text().then(function(b){e([{body:b,status:a.status,
statusText:a.statusText},null])},function(a){e([null,a])})}):"runOAuthFlow"===a.message&&oauthFlow();return!0});chrome.runtime.onInstalled.addListener(function(a){oauthFlow()});function getToken(a){return new Promise(function(d,e){var c={method:"POST",body:JSON.stringify({body:{oauth2_identifier:{type:"google",id_token:a}}}),"Content-Type":"application/json"};fetch(BASE_URL+"/token",c).then(function(a){200===a.status?d(a):e(a)}).catch(function(a){e(a)})})}
function oauthFlow(){var a=chrome.runtime.getManifest(),d=encodeURIComponent(a.oauth2.client_id);a=encodeURIComponent(a.oauth2.scopes.join(" "));var e=encodeURIComponent("urn:ietf:wg:oauth:2.0:oob:auto"),c="https://accounts.google.com/o/oauth2/auth?client_id="+d+"&response_type=id_token&access_type=offline&redirect_uri="+e+"&scope="+a,b=["Success","Denied","Error"];chrome.tabs.create({url:"about:blank"},function(a){chrome.tabs.onUpdated.addListener(function m(d,e,c){if(d===a.id&&null!==c.title&&void 0!==
c.title&&(c=c.title.split(" ",2),e=c[0],2==c.length&&0<=b.indexOf(e)))switch(chrome.tabs.onUpdated.removeListener(m),chrome.tabs.remove(d),d=new URLSearchParams(c[1]),c=null,e){case "Success":c=d.get("id_token");getToken(c).then(function(a){chrome.storage.local.set({authStatus:"Authenticated"})}).catch(function(a){chrome.storage.local.set({authStatus:"Logged Out"});console.log(a)});break;case "Denied":chrome.storage.local.set({authStatus:"Logged Out"});break;case "Error":c=d.get("id_token"),null==
c||void 0==c?chrome.storage.local.set({authStatus:"Logged Out"}):getToken(c).then(function(a){chrome.storage.local.set({authStatus:"Authenticated"})}).catch(function(a){chrome.storage.local.set({authStatus:"Logged Out"});console.log(a)})}});chrome.tabs.update(a.id,{url:c})})};
