var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,c||0)}},"es6","es3");LIST_TYPE="blacklisted-edicratic";
var changeColor=document.getElementById("changeColor"),check=document.getElementById("edicratic-check"),invalidMessage=document.getElementById("edicratic-invalid"),icon=document.getElementById("info-icon-edicratic"),bugReport=document.getElementById("edicratic-bug-report"),buttonIcon=document.getElementById("changeColor-icon"),loader=document.getElementById("loader"),header=document.getElementById("header"),checkBoxAutoCheck=document.getElementById("enable-auto-web-check"),whitelist=document.getElementById("whitelist"),
settings=document.getElementById("edicratic-settings"),clearButton=document.getElementById("clear-html");settings.onclick=function(){return window.open("settings.html","_blank")};header.onclick=function(){return window.open("https://webcheck.edicratic.com/","_blank")};whitelist.onclick=handleWhiteListing;updateBox(checkBoxAutoCheck);updateWhitelist(whitelist);checkBoxAutoCheck.onclick=function(){return handleCheckBoxClick("auto-webcheck-enabled")};bugReport.onclick=handleBugReport;
clearButton.style.display="false"===localStorage.hasHTML?"none":"";clearButton.onclick=function(){return removeAllHTML()};setButtonNormal(changeColor,buttonIcon);function setButtonNormal(a,b){a.style.backgroundColor="";document.getElementById("webcheck-text").textContent="WebCheck This";b.style.display="inline";a.onclick=function(){return performWebCheck()}}
function handleCheckBoxClick(a){chrome.storage.local.get([a],function(b){var c={};c[a]=!1===b[a]?!0:!1;chrome.storage.local.set(c);"auto-webcheck-enabled"===a&&chrome.storage.local.set({"button-change-edicratic":{time:(new Date).getTime(),on:c[a]}})})}function updateBox(a){chrome.storage.local.get(["auto-webcheck-enabled"],function(b){a.checked=!1===b["auto-webcheck-enabled"]?!1:!0})}
function performWebCheck(){chrome.tabs.query({currentWindow:!0,active:!0},function(a){chrome.tabs.executeScript(a[0].id,{code:"chrome.runtime.sendMessage({data: 'webCheckLoadScript', loaded: typeof scriptAlreadyLoaded === \"undefined\" ? false : scriptAlreadyLoaded});"});changeColor.style.display="none";loader&&(loader.style={display:""})})}
function handleBugReport(){request={message:"bugReport"};chrome.tabs.query({currentWindow:!0,active:!0},function(a){var b=a[0];chrome.tabs.insertCSS(b.id,{file:"bugReport.css"});chrome.tabs.executeScript(b.id,{file:"bugReport.js"},function(){chrome.tabs.sendMessage(b.id,request)})})}function removeAllHTML(){chrome.tabs.query({currentWindow:!0,active:!0},function(a){chrome.tabs.sendMessage(a[0].id,{message:"removeAllHTML"})})}
function handleWhiteListing(a){chrome.storage.local.get([LIST_TYPE],function(b){var c=b[LIST_TYPE]||[];console.log(c);chrome.tabs.query({currentWindow:!0,active:!0},function(d){var e=getDomain(d[0].url);a.target.checked?c.push(e):(c=c.filter(function(g){return g!==e}),chrome.storage.local.get(["auto-webcheck-enabled"],function(g){!1!==g["auto-webcheck-enabled"]&&chrome.tabs.sendMessage(d[0].id,{message:"runWebCheck",automatic:!0})}));var f={};f[LIST_TYPE]=c;chrome.storage.local.set(f)})})}
function updateWhitelist(a){chrome.storage.local.get([LIST_TYPE],function(b){var c=b[LIST_TYPE]||[];chrome.tabs.query({currentWindow:!0,active:!0},function(d){d=getDomain(d[0].url);c.includes(d)?a.checked=!0:a.checked=!1})})}function getDomain(a){var b=document.createElement("a");b.href=a;return b.hostname.replace(/.(com|co.uk|net|org|gov|de|edu)/,"")};
