var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};$jscomp.polyfill=function(a,c,b,d){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,d):$jscomp.polyfillUnisolated(a,c,b,d))};
$jscomp.polyfillUnisolated=function(a,c,b,d){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in b))return;b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?d[e]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:c}):c!==b&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("Object.is",function(a){return a?a:function(c,b){return c===b?0!==c||1/c===1/b:c!==c&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(c,b){var d=this;d instanceof String&&(d=String(d));var e=d.length;b=b||0;for(0>b&&(b=Math.max(b+e,0));b<e;b++){var f=d[b];if(f===c||Object.is(f,c))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(c,b){return-1!==$jscomp.checkStringArgs(this,c,"includes").indexOf(c,b||0)}},"es6","es3");LIST_TYPE="blacklisted-edicratic";
var current=[],myNodelist=document.getElementsByTagName("LI"),i;for(i=0;i<myNodelist.length;i++){var span=document.createElement("SPAN"),txt=document.createTextNode("\u00d7");span.className="close";span.appendChild(txt);myNodelist[i].appendChild(span)}chrome.storage.local.get([LIST_TYPE],function(a){current=a=a[LIST_TYPE];for(var c=0;c<a.length;c++)newElement(a[c].toLowerCase(),!0)});var close=document.getElementsByClassName("close");
for(i=0;i<close.length;i++)close[i].onclick=function(){var a=this.parentElement,c=a?a.dataset.content:null;a.style.display="none";c&&chrome.storage.local.get([LIST_TYPE],function(b){b=b[LIST_TYPE];b=b.filter(function(d){return d!==c.replace(".com","")});chrome.storage.local.set(getStorageData(LIST_TYPE,b))})};var list=document.querySelector("ul"),button=document.getElementById("addBtn-edicratic");
button.onclick=function(){var a=document.getElementById("myInput").value;isValidUrl(a)?(a=getDomain(a),newElement(a,!1)):isValidUrl("https://"+a)?(a=getDomain("https://"+a),newElement(a,!1)):isValidUrl("https://www."+a)?(a=getDomain("https://www."+a),newElement(a,!1)):isValidUrl("https://www."+a+".com")?(a=getDomain("https://www."+a+".com"),newElement(a,!1)):isValidUrl("https://"+a+".com")?(a=getDomain("https://"+a+".com"),newElement(a,!1)):alert("Sorry, didn't catch that url")};
function newElement(a,c){if(""!==a){var b=document.createElement("li"),d=document.createTextNode(a);b.setAttribute("data-content",a);b.appendChild(d);document.getElementById("myUL").appendChild(b);document.getElementById("myInput").value="";d=document.createElement("SPAN");var e=document.createTextNode("\u00d7");d.className="close";d.appendChild(e);b.appendChild(d);c||chrome.storage.local.get([LIST_TYPE],function(f){f=f[LIST_TYPE];f.includes(a)?(alert("That seems to be saved already"),b.parentElement.removeChild(b)):
f.push(a);chrome.storage.local.set(getStorageData(LIST_TYPE,f))});for(i=0;i<close.length;i++)close[i].onclick=function(){var f=this.parentElement,g=f?f.dataset.content:void 0;f.style.display="none";g&&chrome.storage.local.get([LIST_TYPE],function(h){h=h[LIST_TYPE];h=h.filter(function(k){return k!==g.replace(".com","")});chrome.storage.local.set(getStorageData(LIST_TYPE,h))})}}}
function getDomain(a){var c=document.createElement("a");c.href=a;return c.hostname.replace(/.(com|co.uk|net|org|gov|de|edu)/,"")}function isValidUrl(a){try{var c=new URL(a);return c.hostname&&c.hostname.match(/^([a-z0-9])(([a-z0-9-]{1,61})?[a-z0-9]{1})?(\.[a-z0-9](([a-z0-9-]{1,61})?[a-z0-9]{1})?)?(\.[a-zA-Z]{2,4})+$/)?!0:!1}catch(b){return!1}}function getStorageData(a,c){var b={};b[a]=c;return b};
